# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ambience}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Harrington"]
  s.date = %q{2009-12-13}
  s.description = %q{JVM-Parameters for your JRuby app}
  s.email = %q{me@rubiii.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/ambience.rb",
     "test/ambience_test.rb",
     "test/fixtures/fixtures.rb",
     "test/fixtures/some_config.yml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/rubiii/ambience}
  s.rdoc_options = ["--charset=UTF-8", "--title", "Ambience", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{JVM-Parameters for your JRuby app}
  s.test_files = [
    "test/ambience_test.rb",
     "test/fixtures/fixtures.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
